const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94763559656"
const SESSION_ID = "PRABATH-MD~9vswjABA#oHnFQUcGLRT4-nT02XwXrsucJpBPWjo8aSBCH1ZOc3s"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
